version: "3.8"

services:
  proxy0:
    image: proxy-web
    container_name: proxy-0
    restart: always
    ports:
      - 8000:8000
    volumes:
      - data-100g:/data

  proxy1:
    image: proxy-web
    container_name: proxy-1
    restart: always
    ports:
      - 8001:8000
    volumes:
      - data-10g-new:/data

  # proxy10g:
  #   image: proxy
  #   container_name: proxy-10g
  #   restart: always
  #   volumes:
  #     - data-10g:/data

  # proxy50g:
  #   image: proxy
  #   container_name: proxy-50g
  #   restart: always
  #   volumes:
  #     - data-50g:/data

  # proxy100g:
  #   image: proxy
  #   container_name: proxy-100g
  #   restart: always
  #   volumes:
  #     - data-100g:/data

volumes:
  proxy-test:
  data-10g:
  data-10g-new:
  data-50g:
  data-100g:

networks:
  default:
    name: ${NETWORK:-ddbs-clusters}
